version: "3.7"
services:
  bot:
    build:
      dockerfile: bot/Dockerfile
      context: "."
    volumes:
      - type: bind
        source: ./.env
        target: /quake3-bot/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true
